### PR TITLE
v0.2.0

### PR DESCRIPTION
**Pull request by malmans2**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by malmans2** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
@malmans2 this should be good to go. Do you want to merge it to check if you have the proper rights here?

**Comment by malmans2** [comment]
@ocefpaf looks like something is not right with the permissions... I can only close or comment this PR.

**Comment by ocefpaf** [comment]
> @ocefpaf looks like something is not right with the permissions... I can only close or comment this PR.

Did you check GH for the invite to be part of the feedstock? Sometimes the e-mail goes to spam. I'll try to update team and see if the bot sends you a new one.

**Comment by malmans2** [comment]
I got the invite... I think I'm all set now! Thanks a lot!

**Pull request merged**
